#
# Copyright (c) Contributors to the Open 3D Engine Project. For complete copyright and license terms please see the LICENSE at the root of this distribution.
# 
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    SceneBuilderConfiguration.h
    SceneImportRequestHandler.h
    SceneImportRequestHandler.cpp
    SceneImporter.h
    SceneImporter.cpp
    SceneSystem.h
    SceneSystem.cpp
    ImportContexts/ImportContexts.h
    ImportContexts/ImportContexts.cpp
    ImportContexts/FbxImportContexts.h
    ImportContexts/FbxImportContexts.cpp
    ImportContexts/AssImpImportContexts.h
    ImportContexts/AssImpImportContexts.cpp
    Importers/FbxAnimationImporter.h
    Importers/FbxAnimationImporter.cpp
    Importers/FbxBoneImporter.h
    Importers/FbxBoneImporter.cpp
    Importers/FbxBlendShapeImporter.h
    Importers/FbxBlendShapeImporter.cpp
    Importers/FbxColorStreamImporter.h
    Importers/FbxColorStreamImporter.cpp
    Importers/FbxTangentStreamImporter.h
    Importers/FbxTangentStreamImporter.cpp
    Importers/FbxBitangentStreamImporter.h
    Importers/FbxBitangentStreamImporter.cpp
    Importers/FbxImporterUtilities.h
    Importers/FbxImporterUtilities.inl
    Importers/FbxImporterUtilities.cpp
    Importers/FbxMaterialImporter.h
    Importers/FbxMaterialImporter.cpp
    Importers/FbxMeshImporter.h
    Importers/FbxMeshImporter.cpp
    Importers/FbxSkinImporter.h
    Importers/FbxSkinImporter.cpp
    Importers/FbxSkinWeightsImporter.h
    Importers/FbxSkinWeightsImporter.cpp
    Importers/FbxTransformImporter.h
    Importers/FbxTransformImporter.cpp
    Importers/FbxUvMapImporter.h
    Importers/FbxUvMapImporter.cpp
    Importers/Utilities/FbxMeshImporterUtilities.h
    Importers/Utilities/FbxMeshImporterUtilities.cpp
    Importers/Utilities/AssImpMeshImporterUtilities.h
    Importers/Utilities/AssImpMeshImporterUtilities.cpp
    Importers/Utilities/RenamedNodesMap.h
    Importers/Utilities/RenamedNodesMap.cpp
    Importers/AssImpAnimationImporter.h
    Importers/AssImpAnimationImporter.cpp
    Importers/AssImpBitangentStreamImporter.h
    Importers/AssImpBitangentStreamImporter.cpp
    Importers/AssImpBlendShapeImporter.h
    Importers/AssImpBlendShapeImporter.cpp
    Importers/AssImpBoneImporter.h
    Importers/AssImpBoneImporter.cpp
    Importers/AssImpColorStreamImporter.h
    Importers/AssImpColorStreamImporter.cpp
    Importers/AssImpImporterUtilities.h
    Importers/AssImpImporterUtilities.cpp
    Importers/AssImpMaterialImporter.h
    Importers/AssImpMaterialImporter.cpp
    Importers/AssImpMeshImporter.h
    Importers/AssImpMeshImporter.cpp
    Importers/AssImpSkinImporter.h
    Importers/AssImpSkinImporter.cpp
    Importers/AssImpSkinWeightsImporter.h
    Importers/AssImpSkinWeightsImporter.cpp
    Importers/AssImpTangentStreamImporter.h
    Importers/AssImpTangentStreamImporter.cpp
    Importers/AssImpTransformImporter.h
    Importers/AssImpTransformImporter.cpp
    Importers/AssImpUvMapImporter.h
    Importers/AssImpUvMapImporter.cpp
    Importers/AssImpAnimationImporter.h
    Importers/AssImpAnimationImporter.cpp
)
