set(GEM_DEPENDENCIES
    Gem::Maestro
    Gem::TextureAtlas
    Gem::LmbrCentral
    Gem::LyShine
    Gem::Camera
    Gem::CameraFramework
    Gem::Atom_RHI.Private
    Gem::EMotionFX
    Gem::Atom_RPI.Private
    Gem::Atom_Feature_Common
    Gem::ImGui
    Gem::Atom_Bootstrap
    Gem::Atom_Component_DebugCamera
    Gem::AtomImGuiTools
    Gem::AtomLyIntegration_CommonFeatures
    Gem::EMotionFX_Atom
    Gem::ImguiAtom
    Gem::Atom_AtomBridge
    Gem::GradientSignal
    Gem::AtomFont
    Gem::Deadhaus_Sonata
	Gem::StartingPointInput
	Gem::ApcAtomExt
	Gem::PhysX
	Gem::ScriptCanvas
	Gem::NvCloth
	Gem::GraphCanvas
	Gem::ScriptEvents
	Gem::ExpressionEvaluation
	
)