
set(GEM_DEPENDENCIES
    Project::Deadhaus_Sonata
    Gem::Maestro
    Gem::TextureAtlas
    Gem::LmbrCentral
    Gem::NvCloth
    Gem::LyShine
    Gem::Camera
    Gem::CameraFramework
    Gem::Atom_RHI.Private
    Gem::EMotionFX
    Gem::Atom_RPI.Private
    Gem::Atom_Feature_Common
    Gem::ImGui
    Gem::Atom_Bootstrap
    Gem::Atom_Component_DebugCamera
    Gem::AtomImGuiTools
    Gem::AtomLyIntegration_CommonFeatures
    Gem::EMotionFX_Atom
    Gem::ImguiAtom
    Gem::Atom_AtomBridge
    Gem::GradientSignal
    Gem::AtomFont
    Gem::WhiteBox
)
